baseurl = "/"
title = "Mutate(City)"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Tiernan Martin"
disqusShortname = "mutate-city"
googleAnalytics = "UA-118875224-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
Paginate = 3

[Author]
    name = "Tiernan Martin"
    profile = "https://twitter.com/maynardandking"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Mutate(City)"
    description = "Data Analytics Applied to the Built Environment"  
    twitter = "https://twitter.com/maynardandking"  
    github = "https://github.com/tiernanmartin" 
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Jan 2"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:slug/"
    note = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Archive"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Portfolio"
    url = "/project/"
    weight = 2
    
[[menu.main]]
    name = "Notepad"
    url = "/note/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
