baseurl = "/"
title = "Mutate(City)"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Tiernan Martin"
disqusShortname = "XXX"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
Paginate = 5

[Author]
    name = "Tiernan Martin"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Mutate(City)"
    description = "Data Science Applied to Urban Planning"
    twitter = "https://twitter.com/maynardandking"
    github = "https://github.com/tiernanmartin" 
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "January 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
